---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment on ${ENV_NAME} enviroment triggered..."
  test-tasks: &test-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Running tests on ${ENV_NAME} enviroment"
pipelines:
  node-microservices:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/MareksPiternieks/ci-junior-2022
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building node application"
      - deploy-dev:
          environemnt_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          environemnt_variables:
            ENV_NAME: DEV
          jobs:
            test:
              tasks: *test-tasks
      - deploy-int:
          environemnt_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          environemnt_variables:
            ENV_NAME: INT
          jobs:
            test:
              tasks: *test-tasks
      - deploy-prd:
          environemnt_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          environemnt_variables:
            ENV_NAME: PRD
          jobs:
            test:
              tasks: *test-tasks
