---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment on ${ENV_NAME} enviroment triggered..."
  test-tasks: &test-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - docker run --network=host -d -t --name api_tests_executor_${ENV_NAME} api_test_executor
    - exec:
        command: bash
        arguments:
          - -c
          - docker exec api_tests_executor_${ENV_NAME} cucumber --tags=@${ENV_NAME} --format html --out test-output/report.html
    - exec:
        command: bash
        arguments:
          - -c
          - docker cp api_tests_executor_${ENV_NAME}:/usr/src/api-tests/test-output/report.html report_${ENV_NAME}.html
    - exec:
        command: bash
        arguments:
          - -c
          - docker rm -f api_tests_executor_${ENV_NAME}

pipelines:
  node-microservices:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/MareksPiternieks/ci-junior-2022
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building node application"
      - deploy-dev:
          environemnt_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          environemnt_variables:
            ENV_NAME: DEV
          jobs:
            test:
              tasks: *test-tasks
      - deploy-int:
          environemnt_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          environemnt_variables:
            ENV_NAME: INT
          jobs:
            test:
              tasks: *test-tasks
      - deploy-prd:
          environemnt_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          environemnt_variables:
            ENV_NAME: PRD
          jobs:
            test:
              tasks: *test-tasks
