---
format_version: 10
pipelines:
  ui-tests:
    group: tests
    materials:
      mygit:
        git: https://github.com/MareksPiternieks/ci-junior-2022
        branch: main
    environemnt_variables:
      TEST_ENVIRONMENT: dev
    stages:
      - test:
          jobs:
            test-chrome:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Running UI tests on ${TEST_ENVIRONMENT} environemnt and chrome browser"
            test-firefox:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Running UI tests on ${TEST_ENVIRONMENT} environemnt and firefox browser"
